/**
 * TASK-F11: governance defaults are owned by this module.
 *
 * Other modules MUST import `DEFAULT_GOVERNANCE_CONFIG` from here (or via the
 * `governance-manager.ts` re-export for backwards compatibility) instead of
 * declaring numeric thresholds inline. `scripts/generate-config-doc.ts`
 * consumes this object to render `docs/configuration.md`'s governance table.
 */

export interface GovernanceMaxCounts {
  skills: number;
  tools: number;
  presets: number;
}

export interface GovernanceThresholds {
  minUsageToKeep: number;
  bugSignalToFlag: number;
}

export interface GovernanceResourceLimits {
  creationsPerDay: number;
  deletionsPerDay: number;
}

export interface GovernanceConfig {
  maxCounts: GovernanceMaxCounts;
  thresholds: GovernanceThresholds;
  resourceLimits: GovernanceResourceLimits;
}

/**
 * Single source of truth for governance defaults. Edits here propagate to:
 *   - `mcp/core/governance/governance-manager.ts` (re-exports the symbol)
 *   - `docs/configuration.md` (regenerated by `npm run docs:config`)
 *   - any handler that imports the constant
 */
export const DEFAULT_GOVERNANCE_CONFIG: GovernanceConfig = {
  maxCounts: {
    skills: 150,
    tools: 150,
    presets: 150
  },
  thresholds: {
    minUsageToKeep: 2,
    bugSignalToFlag: 2
  },
  resourceLimits: {
    creationsPerDay: 5,
    deletionsPerDay: 3
  }
};
