#!/usr/bin/env tsx
import { promises as fsPromises } from "node:fs";
import { dirname, resolve, basename } from "node:path";
import { fileURLToPath } from "node:url";

type DashboardSummary = {
  name: string;
  title: string;
  uid: string;
  schemaVersion: number | "n/a";
  panelCount: number;
  templatePath: string;
  generatedPath: string;
};

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, "..");
const templateDir = resolve(repoRoot, "infra/observability/grafana-dashboards/jsonnet");
const generatedDir = resolve(repoRoot, "infra/observability/grafana-dashboards/generated");
const outputPath = resolve(repoRoot, "docs/generated/features/dashboard-catalog.md");

function toPosixPath(filePath: string): string {
  return filePath.replaceAll("\\", "/");
}

async function readJsonFile(filePath: string): Promise<unknown> {
  const raw = await fsPromises.readFile(filePath, "utf-8");
  return JSON.parse(raw) as unknown;
}

async function collectDashboards(): Promise<DashboardSummary[]> {
  const entries = await fsPromises.readdir(templateDir, { withFileTypes: true });
  const templates = entries
    .filter((entry) => entry.isFile() && entry.name.endsWith(".jsonnet"))
    .map((entry) => resolve(templateDir, entry.name))
    .sort();

  const results: DashboardSummary[] = [];

  for (const templatePath of templates) {
    const name = basename(templatePath, ".jsonnet");
    const generatedPath = resolve(generatedDir, `${name}.json`);

    const templateJson = (await readJsonFile(templatePath)) as Record<string, unknown>;
    const generatedJson = (await readJsonFile(generatedPath)) as Record<string, unknown>;

    const title =
      (typeof generatedJson.title === "string" && generatedJson.title) ||
      (typeof templateJson.title === "string" && templateJson.title) ||
      name;

    const uid =
      (typeof generatedJson.uid === "string" && generatedJson.uid) ||
      (typeof templateJson.uid === "string" && templateJson.uid) ||
      "n/a";

    const schemaVersion =
      typeof generatedJson.schemaVersion === "number"
        ? generatedJson.schemaVersion
        : typeof templateJson.schemaVersion === "number"
          ? templateJson.schemaVersion
          : "n/a";

    const panelCount = Array.isArray(generatedJson.panels)
      ? generatedJson.panels.length
      : Array.isArray(templateJson.panels)
        ? templateJson.panels.length
        : 0;

    results.push({
      name,
      title,
      uid,
      schemaVersion,
      panelCount,
      templatePath: toPosixPath(templatePath.replace(`${repoRoot}\\`, "").replace(`${repoRoot}/`, "")),
      generatedPath: toPosixPath(generatedPath.replace(`${repoRoot}\\`, "").replace(`${repoRoot}/`, ""))
    });
  }

  return results;
}

function renderMarkdown(summaries: DashboardSummary[]): string {
  const lines: string[] = [];
  lines.push("<!-- AUTOGENERATED: do not edit -->");
  lines.push("");
  lines.push("# Dashboard Catalog");
  lines.push("");
  lines.push("> Auto-generated by `scripts/generate-dashboard-catalog.ts`.");
  lines.push(`> Last update: ${new Date().toISOString()}`);
  lines.push(`> Total dashboards: ${summaries.length}`);
  lines.push("");
  lines.push("Run `npm run docs:dashboards` after adding or updating dashboard templates.");
  lines.push("");
  lines.push("| Name | Title | UID | Schema | Panels | Template | Generated JSON |");
  lines.push("|---|---|---|---:|---:|---|---|");

  for (const summary of summaries) {
    lines.push(
      `| ${summary.name} | ${summary.title} | ${summary.uid} | ${summary.schemaVersion} | ${summary.panelCount} | ${summary.templatePath} | ${summary.generatedPath} |`
    );
  }

  lines.push("");
  return `${lines.join("\n")}\n`;
}

async function main(): Promise<void> {
  const summaries = await collectDashboards();
  await fsPromises.mkdir(dirname(outputPath), { recursive: true });
  await fsPromises.writeFile(outputPath, renderMarkdown(summaries), "utf-8");
  console.log(`wrote ${summaries.length} dashboard entries to docs/generated/features/dashboard-catalog.md`);
}

void main().catch((error) => {
  console.error("generate-dashboard-catalog failed:", error instanceof Error ? error.message : String(error));
  process.exitCode = 1;
});
