#!/usr/bin/env -S node --import tsx
import { mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve, relative } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import {
  ERROR_CODES,
  formatMessage,
  type ErrorCode
} from "../mcp/core/errors/messages.js";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, "..");
const outputPath = resolve(repoRoot, "docs", "error-codes.md");

const SAMPLE_PARAMS: Record<ErrorCode, Record<string, unknown>> = {
  INVALID_PATH: { path: "./tmp/invalid", detail: "contains unsupported sequence" },
  PATH_TRAVERSAL: { path: "../secrets.txt" },
  DIRECTORY_NOT_FOUND: { path: "./missing-dir" },
  FILE_NOT_FOUND: { path: "./missing.txt" },
  AMBIGUOUS_NAME: { name: "deploy", candidates: "deploy_org, deployment_plan_generate" },
  TOOL_NOT_FOUND: { name: "unknown_tool" },
  INVALID_INPUT: { field: "topic", detail: "must be non-empty" },
  MISSING_REQUIRED_FIELD: { field: "targetOrg" },
  DUPLICATE_VERSION: { name: "query-skill-model", version: "v1" },
  UNKNOWN_MODEL: { name: "unregistered-model" },
  GIT_COMMAND_FAILED: { command: "git diff", detail: "fatal: not a git repository" },
  INVALID_GIT_REF: { field: "baseBranch", value: "invalid ref" },
  NOT_A_GIT_REPO: { path: "./tmp/no-git" },
  RESOURCE_LIMIT_EXCEEDED: { resource: "skills", detail: "maxCount=150" },
  INTERNAL_ERROR: { detail: "unexpected state" }
};

function renderMarkdown(): string {
  const generatedAt = new Date().toISOString();
  const lines: string[] = [];

  lines.push("# Error Codes");
  lines.push("");
  lines.push("> Auto-generated by scripts/generate-error-codes-doc.ts.");
  lines.push(`> Last update: ${generatedAt}`);
  lines.push("");
  lines.push("## Summary");
  lines.push("");
  lines.push(`- total: ${ERROR_CODES.length}`);
  lines.push("");
  lines.push("## Catalog");
  lines.push("");
  lines.push("| Code | ja | en | Example params |");
  lines.push("|---|---|---|---|");

  for (const code of ERROR_CODES) {
    const params = SAMPLE_PARAMS[code] ?? {};
    const ja = formatMessage(code, params, "ja").replace(/\|/g, "\\|");
    const en = formatMessage(code, params, "en").replace(/\|/g, "\\|");
    const paramsText = JSON.stringify(params).replace(/\|/g, "\\|");
    lines.push(`| ${code} | ${ja} | ${en} | ${paramsText} |`);
  }

  lines.push("");
  lines.push("## Notes");
  lines.push("");
  lines.push("- This file is generated. Do not edit manually.");
  lines.push("- Update mappings in mcp/core/errors/messages.ts and rerun the generator.");

  return lines.join("\n");
}

export async function generateErrorCodesDoc(): Promise<void> {
  const markdown = renderMarkdown();
  await mkdir(dirname(outputPath), { recursive: true });
  await writeFile(outputPath, markdown, "utf-8");
  console.log(`wrote ${ERROR_CODES.length} error codes to ${relative(repoRoot, outputPath)}`);
}

const invokedDirectly = import.meta.url === pathToFileURL(process.argv[1] ?? "").href;
if (invokedDirectly) {
  generateErrorCodesDoc().catch((error) => {
    console.error("generate-error-codes-doc failed:", error);
    process.exit(1);
  });
}
