import { mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { createBuiltinToolRegistry } from "../mcp/core/registry/tool-registry.js";
import { createToolCatalog, type ToolCatalogEntry, type ToolCatalogCategory } from "../mcp/surface/tool-catalog.js";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, "..");
const outputPath = resolve(repoRoot, "docs", "tool-catalog.md");

const CATEGORY_ORDER: ToolCatalogCategory[] = [
  "chat",
  "memory",
  "governance",
  "observability",
  "analysis",
  "deployment",
  "resource",
  "other"
];

function collectCatalogEntries(): ToolCatalogEntry[] {
  const registry = createBuiltinToolRegistry();
  const catalog = createToolCatalog();

  for (const definition of registry.list()) {
    catalog.upsert(definition);
  }

  return catalog.list();
}

function groupByCategoryAndCapability(entries: ToolCatalogEntry[]): Map<ToolCatalogCategory, Map<string, ToolCatalogEntry[]>> {
  const grouped = new Map<ToolCatalogCategory, Map<string, ToolCatalogEntry[]>>();

  for (const entry of entries) {
    const byCapability = grouped.get(entry.category) ?? new Map<string, ToolCatalogEntry[]>();
    const bucket = byCapability.get(entry.capability) ?? [];
    bucket.push(entry);
    byCapability.set(entry.capability, bucket);
    grouped.set(entry.category, byCapability);
  }

  for (const byCapability of grouped.values()) {
    for (const [capability, tools] of byCapability.entries()) {
      byCapability.set(capability, [...tools].sort((a, b) => a.name.localeCompare(b.name)));
    }
  }

  return grouped;
}

function renderMarkdown(entries: ToolCatalogEntry[]): string {
  const generatedAt = new Date().toISOString();
  const grouped = groupByCategoryAndCapability(entries);
  const lines: string[] = [];

  lines.push("<!-- AUTOGENERATED: do not edit -->");
  lines.push("");
  lines.push("# Tool Catalog");
  lines.push("");
  lines.push(`> Auto-generated by scripts/generate-tool-catalog-doc.ts`);
  lines.push(`> Last update: ${generatedAt}`);
  lines.push(`> Total tools: ${entries.length}`);
  lines.push("");
  lines.push("## Index");
  lines.push("");

  for (const category of CATEGORY_ORDER) {
    const categoryEntries = grouped.get(category);
    if (!categoryEntries) continue;
    const capabilityNames = [...categoryEntries.keys()].sort((a, b) => a.localeCompare(b));
    lines.push(`- ${category} (${capabilityNames.length} capabilities)`);
  }

  lines.push("");
  lines.push("## Catalog");
  lines.push("");

  for (const category of CATEGORY_ORDER) {
    const byCapability = grouped.get(category);
    if (!byCapability) continue;

    lines.push(`### ${category}`);
    lines.push("");

    const capabilityNames = [...byCapability.keys()].sort((a, b) => a.localeCompare(b));
    for (const capability of capabilityNames) {
      const tools = byCapability.get(capability) ?? [];
      lines.push(`#### ${capability}`);
      lines.push("");
      lines.push("| Tool | Owner | Since | Deprecated | Replaced By |");
      lines.push("| ---- | ----- | ----- | ---------- | ----------- |");

      for (const tool of tools) {
        lines.push(`| ${tool.name} | ${tool.owner ?? "-"} | ${tool.since ?? "-"} | ${tool.deprecatedAt ?? "-"} | ${tool.replacedBy ?? "-"} |`);
      }
      lines.push("");
    }
  }

  return lines.join("\n");
}

async function main(): Promise<void> {
  try {
    const entries = collectCatalogEntries();
    const markdown = renderMarkdown(entries);
    await mkdir(dirname(outputPath), { recursive: true });
    await writeFile(outputPath, markdown, "utf8");
    console.log(`✓ wrote ${entries.length} tools to docs/tool-catalog.md`);
  } catch (error) {
    console.error("generate-tool-catalog-doc failed:", error instanceof Error ? error.message : String(error));
    process.exit(1);
  }
}

main().catch((error) => {
  console.error("generate-tool-catalog-doc failed:", error);
  process.exit(1);
});
