// Tools reference generator from runtime descriptors.
import { writeFile, mkdir } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import type { ToolDescriptor } from "../mcp/core/registry/tool-descriptor.js";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, "..");
const outputPath = resolve(repoRoot, "docs/generated/features/tools-reference.md");

interface ToolEntry {
  name: string;
  title?: string;
  description?: string;
  capabilities?: string[];
  tags?: string[];
}

async function collectTools(): Promise<ToolEntry[]> {
  // Dynamic import to load registry from compiled mcp/server
  const registryModuleUrl = pathToFileURL(
    resolve(repoRoot, "dist", "mcp", "core", "registry", "tool-registry.js")
  ).href;
  const { createBuiltinToolRegistry } = await import(
    registryModuleUrl
  );

  const registry = createBuiltinToolRegistry();
  const descriptors = registry.listDescriptors();

  return descriptors
    .map((desc: ToolDescriptor): ToolEntry => ({
      name: desc.name,
      title: desc.title,
      description: desc.description,
      capabilities: desc.capabilities,
      tags: desc.tags
    }))
    .sort((a: ToolEntry, b: ToolEntry) => a.name.localeCompare(b.name));
}

function renderMarkdown(tools: ToolEntry[]): string {
  const generatedAt = new Date().toISOString();
  const lines: string[] = [];
  lines.push("<!-- AUTOGENERATED: do not edit -->");
  lines.push("");
  lines.push("# Tools Reference");
  lines.push("");
  lines.push(`> Auto-generated by \`scripts/generate-tools-doc.ts\` from runtime descriptors.`);
  lines.push(`> Last update: ${generatedAt}`);
  lines.push(`> Total tools: ${tools.length}`);
  lines.push("");
  lines.push("Run `npm run docs:tools` after adding or renaming a tool to refresh this file.");
  lines.push("");

  // Index table
  lines.push("## Index");
  lines.push("");
  lines.push("| Name | Title | Capabilities |");
  lines.push("| ---- | ----- | ------------ |");
  for (const tool of tools) {
    const title = tool.title ?? "";
    const caps = tool.capabilities ? tool.capabilities.join(", ") : "";
    lines.push(`| \`${tool.name}\` | ${title} | ${caps} |`);
  }
  lines.push("");

  // Detailed tool entries
  lines.push("## Tool Details");
  lines.push("");
  for (const tool of tools) {
    lines.push(`### \`${tool.name}\``);
    if (tool.title) lines.push(`- **Title**: ${tool.title}`);
    if (tool.description) lines.push(`- **Description**: ${tool.description}`);
    if (tool.capabilities && tool.capabilities.length > 0) {
      lines.push(`- **Capabilities**: ${tool.capabilities.join(", ")}`);
    }
    if (tool.tags && tool.tags.length > 0) {
      lines.push(`- **Tags**: ${tool.tags.join(", ")}`);
    }
    lines.push("");
  }

  return lines.join("\n");
}

async function main(): Promise<void> {
  try {
    const tools = await collectTools();
    const md = renderMarkdown(tools);
    await mkdir(dirname(outputPath), { recursive: true });
    await writeFile(outputPath, md, "utf8");
    console.log(`✓ wrote ${tools.length} tool entries to ${outputPath.replace(repoRoot + "/", "")}`);
  } catch (error) {
    console.error("generate-tools-doc failed:", error instanceof Error ? error.message : String(error));
    process.exit(1);
  }
}

const invokedDirectly = import.meta.url === pathToFileURL(process.argv[1] ?? "").href;
if (invokedDirectly) {
  main().catch((err) => {
    console.error("generate-tools-doc failed:", err);
    process.exit(1);
  });
}

export { main as generateToolsDoc };
