#!/usr/bin/env -S node --import tsx
import { readdir, readFile, stat } from "node:fs/promises";
import { dirname, extname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const AUTOGENERATED_HEADER = "<!-- AUTOGENERATED: do not edit -->";
const CHECK_EXTENSIONS = new Set([".md", ".mdx"]);

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, "..");
const generatedRoot = resolve(repoRoot, "docs", "generated");

async function collectFiles(root: string): Promise<string[]> {
  const files: string[] = [];
  const queue = [root];
  while (queue.length > 0) {
    const current = queue.shift();
    if (!current) continue;
    let entries;
    try {
      entries = await readdir(current, { withFileTypes: true });
    } catch {
      continue;
    }
    for (const entry of entries) {
      const fullPath = join(current, entry.name);
      if (entry.isDirectory()) {
        queue.push(fullPath);
      } else if (entry.isFile()) {
        files.push(fullPath);
      }
    }
  }
  return files;
}

async function main(): Promise<void> {
  const generatedDirStat = await stat(generatedRoot).catch(() => null);
  if (!generatedDirStat?.isDirectory()) {
    console.log("[lint:docs] docs/generated is not present. Skipping for now.");
    return;
  }

  const files = await collectFiles(generatedRoot);
  const targets = files.filter((file) => CHECK_EXTENSIONS.has(extname(file).toLowerCase()));

  const violations: string[] = [];
  for (const filePath of targets) {
    const raw = await readFile(filePath, "utf-8");
    const firstLine = raw.split(/\r?\n/, 1)[0]?.trim() ?? "";
    if (firstLine !== AUTOGENERATED_HEADER) {
      violations.push(filePath.replace(`${repoRoot}\\`, "").replaceAll("\\", "/"));
    }
  }

  if (violations.length > 0) {
    console.error("[lint:docs] Missing autogenerated header:");
    for (const path of violations) {
      console.error(`  - ${path}`);
    }
    process.exitCode = 1;
    return;
  }

  console.log(`[lint:docs] OK (${targets.length} files checked)`);
}

main().catch((error) => {
  console.error(`[lint:docs] Failed: ${error instanceof Error ? error.message : String(error)}`);
  process.exit(1);
});
